添加团队合作教程pdf
TKONIY/Canteen-Info-System pull request #5
Opened 2019-11-23 08:57 UTC by TKONIY

我为文档新建了一个docs分支供大家提交资料和文档，我觉得一些资料文档可以直接merge到master分支，让他们显示在主页上，方便下载和阅读。

2019-11-23 15:05 UTC, buptdjy commented
可以

2019-11-23 15:38 UTC, lochson commented
可以

2019-11-23 17:05 UTC, TKONIY commented
你们不是“可以”就行了，你们还要点击approve，因为你们是reviewer，这个pull request需要4位reviewer点击同意才行。以下教程(不全)截至官方文档，我在ppt里面也发了pull request review的链接，说需要大家回去看的，兄弟们有空认真读一下吧。
![image](https://user-images.githubusercontent.com/47519522/69482426-2e995b00-0e56-11ea-891f-4c93f50f27f8.png)

2019-11-24 08:59 UTC, arnoldzhu approved these changes

2019-11-24 09:11 UTC, lochson approved these changes

2019-11-25 11:37 UTC, lochson approved these changes

2019-11-25 11:37 UTC, lochson approved these changes

2019-11-25 11:38 UTC, will-178 requested changes
好的！

2019-11-25 11:40 UTC, will-178 commented
> 好的！

2019-11-25 14:18 UTC, will-178 approved these changes
我觉得可以！

2019-11-25 16:31 UTC, buptdjy approved these changes

2019-11-25 16:39 UTC, merged