Update README.md
TKONIY/Canteen-Info-System pull request #7
Opened 2019-11-24 13:42 UTC by arnoldzhu

练习运用github desktop，在本地增加了一个feature（对readme少量修改），然后发送一个至dev的pull request

2019-11-24 14:10 UTC, TKONIY requested changes
Binary file is not good.

2019-11-24 17:00 UTC, TKONIY approved these changes

2019-11-24 17:02 UTC, TKONIY commented
Github对READ.md这个文档有一些骚操作，它似乎是可以直接预览md格式的区别。无论如何，提交md格式记得修改为utf-8编码。在查看diff时如果看不到就点一下display the rich diff。问题不大。

2019-11-25 11:43 UTC, lochson approved these changes

2019-11-25 16:32 UTC, buptdjy approved these changes

2019-11-25 16:40 UTC, merged

2019-11-25 17:41 UTC, TKONIY commented
我在merge了这个pull request后删除了featureArnold分支。